# Generated by Django 5.1.1 on 2024-11-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('marks', models.IntegerField()),
            ],
            options={
                'db_table': 'studdent',
            },
        ),
    ]
